services:
  ros:
    build: .
    image: turtlebot3_ws
    container_name: turtlebot3_container

    network_mode: host

    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1

    volumes:
      - .:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    working_dir: /ws

    stdin_open: true
    tty: true

    command: tail -f /dev/null
