services:
  ros:
    build: .
    image: turtlebot3_ws
    container_name: turtlebot3_container

    ports:
      - "5901:5901"

    environment:
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1

    volumes:
      - .:/ws

    working_dir: /ws

    stdin_open: true
    tty: true

    command: tail -f /dev/null